# === Production Dockerfile ===
FROM oven/bun:1-alpine
COPY good-food-contracts /good-food-contracts
WORKDIR /app
COPY package.json bun.lockb* bun.lock* ./
RUN bun install --production --no-frozen-lockfile
COPY . .
# No prisma generate needed for catalog-service
EXPOSE 8080
CMD ["bun", "run", "src/app.ts"]
