# === Production Dockerfile ===
FROM oven/bun:1-alpine
COPY good-food-contracts /good-food-contracts
WORKDIR /app
COPY package.json bun.lockb* ./
RUN bun install --production
COPY . .
# Removed prisma generate as this service doesn't use it
EXPOSE 8080
CMD ["bun", "run", "src/app.ts"]
